### ISSUE TITLE
CUDA out of memory. Can this be run on a p3.16xlarge?

### ISSUE THREAD

**Issue by rileyhun** [databrickslabs/dolly#140]
I am training using the `EleutherAI/pythia-2.8b` model and I'm using a `p3.16xlarge`. I tried the instructions for training on smaller instances, but still got a `CUDA out of memory` error on epoch 0.14. Aside from that, I wasn't able to use a batch size of 3. I had to reduce to 1.  I'm also using 8 GPUs. 

Here is my deepseed config:

```
{
  "fp16": {
        "enabled": true,
        "auto_cast": false,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
        "device": "cpu",
        "pin_memory": true
    },
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

Any advice?

**Comment by srowen** [comment]
See guidance here: https://github.com/databrickslabs/dolly#v100-gpus-1
p3dn.24xlarge (32GB V100s) would be better. That's a 16GB V100. You may be able to make it work by configuring optimizer offload _and_ turning down batch size.

**Comment by rileyhun** [comment]
Thanks for the guidance. Yeah I tried following all of those suggestions already. I am offloading optimize to cpu AND reduced batch size to 1, but sadly still runs into CUDA OOM Error. Not very efficient either. Took 3 hours to get to epoch 0.14 and then eventually got the OOM Error.

**Comment by srowen** [comment]
16GB is small for training, yeah. You can try param offload too. But then it'll be slower. You want bigger GPUs - maybe g5 / A10?

**Comment by rileyhun** [comment]
Tried A10 (g5.48xlarge) and got this error:

```
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1659484809535/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, unhandled system error, NCCL version 2.10.3
2023-04-29 23:39:39.643 [183/train/596 (pid 11451)] [b297bdd1-7d34-4c4b-9f18-5c39b4ca48b5] ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. It can be also caused by unexpected exit of a remote peer, you can check NCCL warnings for failure reason and see if there is connection closure by a peer.
```

**Comment by srowen** [comment]
Never seen that one - are there other errors? this is just saying "something went wrong". Make sure you made all the settings in the notebook, and suggest configurations. It definitely runs for me as-is on a g5, with less memory even.

**Comment by css459** [comment]
Hello! I was considering making a thread, but figured this one was relevant enough that I would ask here instead. I'm trying to train the 7B variant on g5.4xlarge. I load the model using `half()` and that seems to work well and sits about 14GB out of 24GB on the GPU. I also followed the recommended instructions for A10s, and my config looks like the one above.

However, Deepspeed keeps getting OOM killed--Presumably the offloaded optimizer is overloading the CPU RAM? I don't see a similar spike to VRAM. I know backward passes can be memory bound, but this machine has 64GB of RAM. 

Is there anything else I can try here? Or if I need a more powerful instance, can you recommend the amount of RAM I might need. I might give PEFT/LORA a try if you have any insight into the model performance implications of training in that way. Thanks!!

**Comment by srowen** [comment]
OOM on the GPU or VM? You are following https://github.com/databrickslabs/dolly#a10-gpus-1 right?
That instance was enough IIRC to train 7B, or at least it started to. If it fails late in the training, let me know

**Comment by css459** [comment]
This is CPU RAM OOM that I confirmed with `nvidia-smi` and `htop`. I receive `exits with return code = -9` It happens I think on the first backward call. For reference, I also tried this on the dolly dataset to confirm its not a data issue. I tried with both deepspeed and without. 

The best I could get working is 3B with memory pinning turned off (but CPU offloading turned on).  This machine has a single A10, do you feel that alone is sufficient for training 7B?

In my experience with similarly large seq2seq models, this shouldn't be a problem. The OP above is running 2.8B on 256GB of VRAM, so I wonder if they are encountering a similar runaway memory issue. 

Happy to share any other info if it helps. Most of the `trainer.py` file seems to be a typical HF Trainer setup, aside from the Data collator--Anything worth investigating there?

**Comment by srowen** [comment]
Oh, you are trying to train on a g5.4xlarge? I misread, crossed it with the OP's thread. That's too little mem. You want a multi-GPU setup with more mem like the g5.24xlarge, with 4 GPUs (96GB per GPU vs 64GB).  I can tell you that worked comfortably for me. The model itself is 28GB in mem, and (I assume) when you account for all the copying and other stuff that has to load in mem, including all your optimizer offload state, that just isn't enough working room.

**Comment by css459** [comment]
No problem will try and report back! Thank you for your help

**Comment by rileyhun** [comment]
I think it's something to do with my nvidia driver, maybe? 

Getting these in the logs after I set `NCCL_DEBUG=INFO`

```
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1] NCCL INFO Failed to open libibverbs.so[.1]
NCCL INFO P2P is disabled between connected GPUs 3 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
```

**Comment by srowen** [comment]
Yep, doesn't look right. Not sure how you have set up the instance, so pretty hard to debug. Probably mismatched versions of CUDA libraries.

**Comment by rileyhun** [comment]
Managed to get my hands on a p3dn.24xlarge. Was surprised that it was still failing at epoch 0.14. Always seems to fail around there with OOM. Tried batch size 3. Could try batch size 2 but wouldn't be very efficient and would certainly be costly as well.

**Comment by css459** [comment]
Just to confirm, the training code will filter your inputs for you right? From what I see in the Pythia configs, all the models have a max input size of 2048 (while the other dimension of the input matrix could be 4096, etc.)

**Comment by srowen** [comment]
I don't think you're hitting the model's limit, but running out of memory fitting 2 or 1 batches of less than that in memory

**Comment by css459** [comment]
Thanks Sean as well for all your help and great support for the project!

**Comment by srowen** [comment]
That doesn't sound right, yes. The 3B model was working OK for me on the 32GB V100s, though I didn't run to completion for testing. I didn't make more deepspeed config changes. Does batch size of 1 work? Or: enable the optimizer offload as in the docs. I'd do that before truncating inputs, though, you could try that too.

**Comment by rileyhun** [comment]
I think I am out of the woods now in terms of CUDA OOM Error. Managed to get it up to **epoch 0.28**, but ran into a different error. I got

```
RuntimeError("Could not find response key token IDs")
```

I suppose not all the input data will have the `RESPONSE KEY` token ?

https://github.com/databrickslabs/dolly/blob/5f9bfba300181fb35854d64c8bf1180ea75105f7/training/trainer.py#LL64C1-L67C18

**Comment by srowen** [comment]
If you're truncating then yeah this is the problem that would cause. If you go that route just throw out long input entirely

**Comment by rileyhun** [comment]
Got it - makes sense!

**Comment by rileyhun** [comment]
Thanks for your help. Successfully got it working now. Closing this issue now.
