### ISSUE TITLE
Dolly deepspeed fine-tuning hangs with multiple GPU nodes

### ISSUE THREAD

**Issue by XinliYu** [databrickslabs/dolly#98]
Dolly deepspeed fine-tuning works on a single GPU node but it hangs on two GPU nodes.

Here are the commandlines I am using. When using a single node, simply set `--nnode=1 --node_rank=0` and it works.

```
python -m torch.distributed.run --nproc_per_node=8 --nnode=2 --node_rank=0 --master_addr=10.0.24.29 --master_port=9901 trainer.py \
    --input-model 'databricks/dolly-v2-7b' \
    --local-output-dir './train_output_7b' \
    --dbfs-output-dir './train_output_dbfs_7b' \
    --per-device-train-batch-size 6 \
    --per-device-eval-batch-size 6 \
    --warmup-steps 50 \
    --deepspeed ds_z3_bf16_config.json

python -m torch.distributed.run --nproc_per_node=8 --nnode=2 --node_rank=1 --master_addr=10.0.24.29 --master_port=9901 trainer.py \
    --input-model 'databricks/dolly-v2-7b' \
    --local-output-dir './train_output_7b' \
    --dbfs-output-dir './train_output_dbfs_7b' \
    --per-device-train-batch-size 6 \
    --per-device-eval-batch-size 6 \
    --warmup-steps 50 \
    --deepspeed ds_z3_bf16_config.json
```

The timeout message is as the following. This does not happen for another model on exactly the same machines. Anyone else has similar experience?

```
[E ProcessGroupNCCL.cpp:821] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1803837 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1803973 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804382 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804393 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804398 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=391, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804838 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=391, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804883 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=391, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804992 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1803973 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1803837 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=391, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804992 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804382 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=389, OpType=_REDUCE_SCATTER_BASE, Timeout(ms)=1800000) ran for 1804398 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 92932 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 92933 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 92934 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 92935 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 4 (pid: 92936) of binary: /home/ec2-user/anaconda3/envs/pytorch_p38/bin/python
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ec2-user/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

```

I also see a warning in the log message "UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead"; not sure if this is related.

**Comment by srowen** [comment]
Works for me, but you need sufficient hardware. What hardware? what model size?
Looks like you're running this yourself so not sure what other changes or differences are relevant.
The provided training code works; see the README for more info on modifying for smaller instances.

**Comment by XinliYu** [comment]
Hi Sean, thanks for your quick response! Are you using the deepspeed command line in the `train_dolly.py` script?

My instance should be sufficiently big, both are p4.24dxlarge, so i assume this is not a hardware issue.

**Comment by srowen** [comment]
Yes. It looks like you're running this by hand across a cluster, which probably totally works, but I assume the issue is somewhere in that setup. The provided training script assumes just a single p4dn.24xlarge. Can the two instances actually communicate?

**Comment by matthayes** [comment]
Also are you providing the instances to train with using the deepspeed hostfile if it is the case that you are using multiple machines?
